import './aside.scss';

//------------------ASIDE
const asideBlock = createElement('aside', 'main__aside') as HTMLElement;
const buttonContainer = createElement('div', 'btn__container') as HTMLDivElement;
const buttonReset = createElement('button', 'btn__reset') as HTMLButtonElement;
const buttonCopy = createElement('button', 'btn__copy') as HTMLButtonElement;
const filterCategory = createElement('div', 'filter__category') as HTMLDivElement;
const filterSubcategory = createElement('div', 'filter__subcategory') as HTMLDivElement;
const filterPrice = createElement('div', 'filter__price') as HTMLDivElement;
const filterCategoryHeader = createElement('h3', 'filter-category-title') as HTMLHeadingElement;
const filterSubcategoryHeader = createElement('h3', 'filter-subcategory-title') as HTMLHeadingElement;
const filterPriceHeader = createElement('h3', 'filter-price-title') as HTMLHeadingElement;
const categoryForm = createElement('form', 'form__category') as HTMLFormElement;
const subcategoryForm = createElement('form', 'form__category') as HTMLFormElement;
const categoryFormLabelSport = createElement('label', 'category-label') as HTMLInputElement;
const categoryFormLabelClothes = createElement('label', 'category-label') as HTMLInputElement;
const categoryFormLabelMagicItems = createElement('label', 'category-label') as HTMLInputElement;
const categoryFormLabelPotions = createElement('label', 'category-label') as HTMLInputElement;
const categoryFormLabelAuto = createElement('label', 'category-label') as HTMLInputElement;
const categoryFormLabelMagicalCreatures = createElement('label', 'category-label') as HTMLInputElement;
const subcategoryFormLabelSticks = createElement('label', 'subcategory-label') as HTMLInputElement;
const subcategoryFormLabelStones = createElement('label', 'subcategory-label') as HTMLInputElement;
const subcategoryFormLabelInteriorItems = createElement('label', 'subcategory-label') as HTMLInputElement;
const subcategoryFormLabelBooks = createElement('label', 'subcategory-label') as HTMLInputElement;
const subcategoryFormLabelWeapon = createElement('label', 'subcategory-label') as HTMLInputElement;
const subcategoryFormLabelCLothes = createElement('label', 'subcategory-label') as HTMLInputElement;
const subcategoryFormLabelAccessories = createElement('label', 'subcategory-label') as HTMLInputElement;
const subcategoryFormLabelFlyingObjects = createElement('label', 'subcategory-label') as HTMLInputElement;
const subcategoryFormLabelGoodPotions = createElement('label', 'subcategory-label') as HTMLInputElement;
const subcategoryFormLabelPositiveBeings = createElement('label', 'subcategory-label') as HTMLInputElement;
const subcategoryFormLabelNegativeBeings = createElement('label', 'subcategory-label') as HTMLInputElement;
const checkbox = createElement('div', 'checkbox') as HTMLDivElement;
const categoryFormInputSport = createElement('input', 'category-input') as HTMLInputElement;
const categoryFormInputClothes = createElement('input', 'category-input') as HTMLInputElement;
const categoryFormInputMagicItems = createElement('input', 'category-input') as HTMLInputElement;
const categoryFormInputPotions = createElement('input', 'category-input') as HTMLInputElement;
const categoryFormInputAuto = createElement('input', 'category-input') as HTMLInputElement;
const categoryFormInputMagicalCreatures = createElement('input', 'category-input') as HTMLInputElement;
const subcategoryFormInputSticks = createElement('input', 'subcategory-input') as HTMLInputElement;
const subcategoryFormInputStones = createElement('input', 'subcategory-input') as HTMLInputElement;
const subcategoryFormInputInteriorItems = createElement('input', 'subcategory-input') as HTMLInputElement;
const subcategoryFormInputBooks = createElement('input', 'subcategory-input') as HTMLInputElement;
const subcategoryFormInputWeapon = createElement('input', 'subcategory-input') as HTMLInputElement;
const subcategoryFormInputCLothes = createElement('input', 'subcategory-input') as HTMLInputElement;
const subcategoryFormInputAccessories = createElement('input', 'subcategory-input') as HTMLInputElement;
const subcategoryFormInputFlyingObjects = createElement('input', 'subcategory-input') as HTMLInputElement;
const subcategoryFormInputGoodPotions = createElement('input', 'subcategory-input') as HTMLInputElement;
const subcategoryFormInputPositiveBeings = createElement('input', 'subcategory-input') as HTMLInputElement;
const subcategoryFormInputNegativeBeings = createElement('input', 'subcategory-input') as HTMLInputElement;
const rangeContainer = createElement('div', 'range-container') as HTMLDivElement;
const sliderControl = createElement('div', 'slider-control') as HTMLDivElement;
const formControl = createElement('div', 'form-control') as HTMLDivElement;
const formControlContainerMin = createElement('div', 'form-control-container') as HTMLDivElement;
const formControlContainerMax = createElement('div', 'form-control-container') as HTMLDivElement;
const formControlContainerMinTime = createElement('div', 'form-control-container__time') as HTMLDivElement;
const formControlContainerMaxTime = createElement('div', 'form-control-container__time') as HTMLDivElement;
const sliderInputFrom = createElement('input', 'from-slider') as HTMLInputElement;
const sliderInputTo = createElement('input', 'to-slider') as HTMLInputElement;
const formControlTimeInputMin = createElement('input', 'form_control_container__time__input_min') as HTMLInputElement;
const formControlTimeInputMax = createElement('input', 'form_control_container__time__input_max') as HTMLInputElement;
buttonReset.textContent = 'сбросить';
buttonCopy.textContent = 'скопировать';

filterCategoryHeader.textContent = 'Категории';
filterSubcategoryHeader.textContent = 'Подкатегории';
filterPriceHeader.textContent = 'Цена';
categoryFormLabelAuto.textContent = 'Транспорт';
categoryFormLabelClothes.textContent = 'Одежда и аксессуары';
categoryFormLabelMagicItems.textContent = 'Магические предметы';
categoryFormLabelPotions.textContent = 'Зелья';
categoryFormLabelSport.textContent = 'Спорт';
categoryFormLabelMagicalCreatures.textContent = 'Магические существа';
subcategoryFormLabelAccessories.textContent = 'Аксессуары';
subcategoryFormLabelBooks.textContent = 'Книжные товары';
subcategoryFormLabelCLothes.textContent = 'Одежда';
subcategoryFormLabelFlyingObjects.textContent = 'Летающие объекты';
subcategoryFormLabelGoodPotions.textContent = 'Добрые зелья';
subcategoryFormLabelInteriorItems.textContent = 'Предметы интерьера';
subcategoryFormLabelSticks.textContent = 'Волшебные палочки';
subcategoryFormLabelStones.textContent = 'Камни';
subcategoryFormLabelWeapon.textContent = 'Оружие';
subcategoryFormLabelPositiveBeings.textContent = 'Положительные существа';
subcategoryFormLabelNegativeBeings.textContent = 'Отрицательные существа';

sliderInputFrom.type = 'range';
sliderInputTo.type = 'range';
sliderInputFrom.value = '0';
sliderInputFrom.min = '0';
sliderInputFrom.max = '100';
sliderInputTo.value = '100';
sliderInputTo.min = '0';
sliderInputTo.max = '100';

formControlTimeInputMin.type = 'number';
formControlTimeInputMax.type = 'number';
formControlTimeInputMin.value = '0';
formControlTimeInputMax.value = '100';
formControlContainerMinTime.textContent = 'Min';
formControlContainerMaxTime.textContent = 'Max';

formControlContainerMin.append(formControlContainerMinTime);
formControlContainerMin.append(formControlTimeInputMin);
formControlContainerMax.append(formControlContainerMaxTime);
formControlContainerMax.append(formControlTimeInputMax);
formControl.append(formControlContainerMin);
formControl.append(formControlContainerMax);
sliderControl.append(sliderInputFrom);
sliderControl.append(sliderInputTo);
rangeContainer.append(sliderControl);
rangeContainer.append(formControl);

categoryFormLabelAuto.append(categoryFormInputAuto);
categoryFormLabelClothes.append(categoryFormInputClothes);
categoryFormLabelMagicItems.append(categoryFormInputMagicItems);
categoryFormLabelPotions.append(categoryFormInputPotions);
categoryFormLabelSport.append(categoryFormInputSport);
categoryFormLabelMagicalCreatures.append(categoryFormInputMagicalCreatures);
subcategoryFormLabelAccessories.append(subcategoryFormInputAccessories);
subcategoryFormLabelBooks.append(subcategoryFormInputBooks);
subcategoryFormLabelCLothes.append(subcategoryFormInputCLothes);
subcategoryFormLabelFlyingObjects.append(subcategoryFormInputFlyingObjects);
subcategoryFormLabelGoodPotions.append(subcategoryFormInputGoodPotions);
subcategoryFormLabelInteriorItems.append(subcategoryFormInputInteriorItems);
subcategoryFormLabelSticks.append(subcategoryFormInputSticks);
subcategoryFormLabelStones.append(subcategoryFormInputStones);
subcategoryFormLabelWeapon.append(subcategoryFormInputWeapon);
subcategoryFormLabelPositiveBeings.append(subcategoryFormInputPositiveBeings);
subcategoryFormLabelNegativeBeings.append(subcategoryFormInputNegativeBeings);

asideBlock.append(buttonContainer);
buttonContainer.append(buttonReset);
buttonContainer.append(buttonCopy);
asideBlock.append(filterCategory);
asideBlock.append(filterSubcategory);
asideBlock.append(filterPrice);
filterCategory.append(filterCategoryHeader);
filterSubcategory.append(filterSubcategoryHeader);
filterPrice.append(filterPriceHeader);
filterPrice.append(rangeContainer);
filterCategory.append(categoryForm);
filterSubcategory.append(subcategoryForm);
categoryForm.append(categoryFormLabelAuto);
categoryForm.append(categoryFormLabelClothes);
categoryForm.append(categoryFormLabelMagicItems);
categoryForm.append(categoryFormLabelPotions);
categoryForm.append(categoryFormLabelSport);
categoryForm.append(categoryFormLabelMagicalCreatures);
subcategoryForm.append(subcategoryFormLabelAccessories);
subcategoryForm.append(subcategoryFormLabelBooks);
subcategoryForm.append(subcategoryFormLabelCLothes);
subcategoryForm.append(subcategoryFormLabelFlyingObjects);
subcategoryForm.append(subcategoryFormLabelGoodPotions);
subcategoryForm.append(subcategoryFormLabelInteriorItems);
subcategoryForm.append(subcategoryFormLabelSticks);
subcategoryForm.append(subcategoryFormLabelStones);
subcategoryForm.append(subcategoryFormLabelWeapon);
subcategoryForm.append(subcategoryFormLabelPositiveBeings);
subcategoryForm.append(subcategoryFormLabelNegativeBeings);
